// Rock Drill Checklist — searchable PDF mirroring the paper form.
import { pdf } from '@react-pdf/renderer';
import { db } from '@/db';
import { formatDate } from '@/lib/utils';
import {
  DRILL_DAILY_CHECKS,
  DRILL_WEEKLY_CHECKS,
  type CheckState,
  type DrillChecklist,
  type Equipment,
  type Job,
} from '@/db/schema';
import {
  CHECK,
  Document,
  Footer,
  HeaderBar,
  K,
  LV,
  Page,
  Signature,
  T,
  TD,
  TR,
  Text,
  View,
  blobToDataUrl,
} from './kit';

const STATE_LABEL: Record<CheckState, string> = { ok: CHECK, na: 'N/A', skip: '—' };

interface Data {
  checklist: DrillChecklist;
  rig?: Equipment;
  job?: Job;
  companyName: string;
  sigUrl: string | null;
}

function ChecklistDoc({ checklist, rig, job, companyName, sigUrl }: Data) {
  return (
    <Document title={`Rock Drill Checklist — ${formatDate(checklist.date)}`}>
      <Page size="LETTER" style={K.page}>
        <HeaderBar companyName={companyName} title="Rock Drill Checklist" />
        <T style={{ marginBottom: 6 }}>
          <TR>
            <TD><LV label="Drill:" value={rig ? `${rig.assetNumber} — ${rig.description}` : checklist.equipmentId} /></TD>
            <TD w={110}><LV label="Date:" value={formatDate(checklist.date)} /></TD>
            <TD w={110}><LV label="Starting hours:" value={checklist.startingHours ?? '—'} /></TD>
          </TR>
          <TR>
            <TD><LV label="Job:" value={job?.name ?? '—'} /></TD>
            <TD w={220}><LV label="Operator:" value={checklist.drillerName} /></TD>
          </TR>
        </T>
        <T style={{ marginBottom: 6 }}>
          <TR shade>
            <TD textStyle={K.bold}>Daily checks</TD>
            <TD w={70} textStyle={[K.bold, K.center]}>Status</TD>
          </TR>
          {DRILL_DAILY_CHECKS.map((key) => (
            <TR key={key}>
              <TD>{key}</TD>
              <TD w={70} textStyle={K.center}>{STATE_LABEL[checklist.daily[key] ?? 'skip']}</TD>
            </TR>
          ))}
        </T>
        <T style={{ marginBottom: 6 }}>
          <TR shade>
            <TD textStyle={K.bold}>{`Weekly checks${checklist.weeklyDone ? '' : ' (not due)'}`}</TD>
            <TD w={70} textStyle={[K.bold, K.center]}>Status</TD>
          </TR>
          {DRILL_WEEKLY_CHECKS.map((key) => (
            <TR key={key}>
              <TD>{key}</TD>
              <TD w={70} textStyle={K.center}>
                {checklist.weeklyDone ? STATE_LABEL[checklist.weekly[key] ?? 'skip'] : '—'}
              </TD>
            </TR>
          ))}
        </T>
        <T>
          <TR>
            <TD>
              <Text>
                <Text style={K.bold}>Repairs needed: </Text>
                <Text>{checklist.repairsNote || 'none'}</Text>
                {checklist.outOfService ? <Text style={K.bold}> — OUT OF SERVICE</Text> : null}
              </Text>
            </TD>
          </TR>
          <TR>
            <TD>
              <View style={{ flexDirection: 'row', alignItems: 'flex-end' }}>
                <Text style={K.bold}>Operator signature: </Text>
                <Signature dataUrl={sigUrl} height={30} />
              </View>
            </TD>
          </TR>
        </T>
        <Footer text={`Generated by ShotLog — ${companyName} — ${formatDate(checklist.date)}`} />
      </Page>
    </Document>
  );
}

export async function buildChecklistPdf(checklistId: string): Promise<Blob> {
  const checklist = await db.drillChecklists.get(checklistId);
  if (!checklist) throw new Error('checklist not found');
  const rig = await db.equipment.get(checklist.equipmentId);
  const job = checklist.jobId ? await db.jobs.get(checklist.jobId) : undefined;
  const company = await db.companySettings.get('companySettings-singleton');
  const sigUrl =
    checklist.signatureImage instanceof Blob && checklist.signatureImage.size > 0
      ? await blobToDataUrl(checklist.signatureImage)
      : null;
  return pdf(
    <ChecklistDoc
      checklist={checklist}
      rig={rig}
      job={job}
      companyName={company?.companyName || 'Baystate Blasting, Inc.'}
      sigUrl={sigUrl}
    />,
  ).toBlob();
}
