// Daily Report + Materials Summary — searchable PDF matching Baystate's
// paper form (same structure as PrintDailyReportPage).
import { pdf } from '@react-pdf/renderer';
import { db } from '@/db';
import { getJobView } from '@/lib/jobContext';
import type {
  BlastDay,
  DailyReport,
  EquipmentEntry,
  ExplosiveUsage,
  Job,
  MaterialEntry,
  ProductCategory,
  Shot,
  SubcontractorEntry,
  WorkForceEntry,
} from '@/db/schema';
import { CHECK, Document, Footer, K, Page, T, TD, TR, Text, View, dash, fmtDate } from './kit';

const AGENT_CATEGORIES: ProductCategory[] = ['bulk', 'anfo', 'anfo_wr', 'emulsion'];
const HE_CATEGORIES: ProductCategory[] = ['gel_dynamite', 'cartridge'];
const BOOSTER_CATEGORIES: ProductCategory[] = ['booster', 'booster_electronic'];
const DOW = ['M', 'T', 'W', 'T', 'F', 'S'];

interface Data {
  blastDay: BlastDay;
  job?: Job;
  dailyReport: DailyReport;
  shots: Shot[];
  explosiveUsage?: ExplosiveUsage;
  workForce: WorkForceEntry[];
  equipment: EquipmentEntry[];
  materials: MaterialEntry[];
  subcontractors: SubcontractorEntry[];
}

/** Option strip with the selected value "circled" (bordered chip in PDF). */
function CondCell({
  title,
  options,
  value,
  w,
}: {
  title: string;
  options: { key: string; label: string }[];
  value: string;
  w: number;
}) {
  return (
    <TD w={w} style={{ paddingVertical: 3 }}>
      <Text style={[K.bold, K.center, { fontSize: 7, marginBottom: 1.5 }]}>{title}</Text>
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center' }}>
        {options.map((opt) => (
          <Text
            key={opt.key}
            style={[
              { fontSize: 6, marginHorizontal: 1.5, marginVertical: 0.5, paddingHorizontal: 2, paddingVertical: 0.5 },
              opt.key === value
                ? { borderWidth: 1, borderColor: '#000', borderRadius: 5, fontFamily: 'Helvetica-Bold' }
                : {},
            ]}
          >
            {opt.label}
          </Text>
        ))}
      </View>
    </TD>
  );
}

function DailyReportDoc(d: Data) {
  const { blastDay, job, dailyReport, shots, explosiveUsage, workForce, equipment, materials, subcontractors } = d;
  const dow = new Date(`${blastDay.date}T12:00:00`).getDay();

  const totalHoles = shots.reduce((s, sh) => s + sh.totals.numHoles, 0);
  const totalFootage = shots.reduce((s, sh) => s + sh.totals.totalDrillFootage, 0);
  const pattern = shots[0]?.drillParams.burden
    ? `${shots[0].drillParams.burden}×${shots[0].drillParams.spacing}`
    : '';

  type EquipCell = { label?: string; item?: EquipmentEntry };
  const equipCells: EquipCell[] = [
    { label: 'Vehicles' },
    ...equipment.filter((e) => e.category === 'vehicle').map((item) => ({ item })),
    { label: 'Equip / Drills' },
    ...equipment.filter((e) => e.category === 'equip_drill').map((item) => ({ item })),
    { label: 'Mats / Seismo' },
    ...equipment.filter((e) => e.category === 'mats_seismo').map((item) => ({ item })),
  ];
  const wfRowCount = Math.max(10, workForce.length, equipCells.length);
  const wfRows: (WorkForceEntry | undefined)[] = Array.from({ length: wfRowCount }, (_, i) => workForce[i]);

  const products = explosiveUsage?.products ?? [];
  const lbsIn = (cats: ProductCategory[]) =>
    products.filter((p) => cats.includes(p.category as ProductCategory)).reduce((s, p) => s + p.totalWeight, 0);
  const agentLbs = lbsIn(AGENT_CATEGORIES);
  const heLbs = lbsIn(HE_CATEGORIES);
  const boosterLbs = lbsIn(BOOSTER_CATEGORIES);
  const detonators = explosiveUsage?.detonators ?? [];
  const detonatorCount = detonators.reduce((s, dd) => s + dd.quantity, 0);
  const totalLbs = explosiveUsage?.totalPoundsShot ?? 0;
  const summaryGroups: { title: string; cats: ProductCategory[]; unit: string }[] = [
    { title: 'Blasting Agents', cats: AGENT_CATEGORIES, unit: 'LB' },
    { title: 'High Explosives', cats: HE_CATEGORIES, unit: 'LB' },
    { title: 'Boosters', cats: BOOSTER_CATEGORIES, unit: 'EA' },
  ];
  const wfHead = (t: string, w?: number) => (
    <TD w={w} textStyle={[K.bold, K.center, { fontSize: 7 }]}>{t}</TD>
  );
  const footer = `Generated by ShotLog — Baystate Blasting, Inc. — ${fmtDate(blastDay.date)}`;

  return (
    <Document title={`Daily Report — ${blastDay.date}`}>
      {/* ============ PAGE 1: DAILY REPORT ============ */}
      <Page size="LETTER" style={K.page}>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 }}>
          <View style={{ flex: 1 }}>
            <Text style={{ fontSize: 15, fontFamily: 'Helvetica-Bold' }}>
              BAYSTATE BLASTING, INC - DAILY REPORT
            </Text>
            <Text style={{ fontSize: 6.5, color: '#666', marginTop: 1 }}>100 Air Mile Exemption (395.1)</Text>
          </View>
          <View style={{ alignItems: 'center' }}>
            <Text style={[K.val, { fontSize: 12, borderWidth: 1.5, borderColor: '#000', paddingHorizontal: 6, paddingVertical: 2 }]}>
              {fmtDate(blastDay.date)}
            </Text>
            <Text style={{ fontSize: 7, marginTop: 1.5 }}>
              {DOW.map((label, i) => (i + 1 === dow ? `(${label}) ` : `${label} `)).join('')}
            </Text>
          </View>
        </View>

        <T style={{ marginBottom: 4 }}>
          <TR>
            <TD>
              <Text>
                <Text>Customer: </Text>
                <Text style={K.val}>{job?.customer ?? ''}</Text>
              </Text>
            </TD>
            <TD>
              <Text>
                <Text>Address: </Text>
                <Text style={K.val}>{[job?.address, job?.city, job?.state].filter(Boolean).join(', ')}</Text>
              </Text>
            </TD>
          </TR>
        </T>

        {/* Conditions bar */}
        <T style={{ marginBottom: 4 }}>
          <TR>
            <CondCell
              title="Temperature"
              options={[{ key: 'low', label: 'LOW' }, { key: 'mod', label: 'MOD' }, { key: 'high', label: 'HIGH' }]}
              value={blastDay.conditions.temperatureRange}
              w={95}
            />
            <CondCell
              title="Weather"
              options={[
                { key: 'sunny', label: 'SUNNY' },
                { key: 'cloudy', label: 'CLOUDY' },
                { key: 'partly_cloudy', label: 'PARTLY CLOUDY' },
                { key: 'rain_light', label: 'RAIN: LIGHT' },
                { key: 'rain_heavy', label: 'HEAVY' },
                { key: 'rain_out', label: 'RAIN OUT' },
              ]}
              value={blastDay.conditions.weather}
              w={165}
            />
            <CondCell
              title="Ground Conditions"
              options={[
                { key: 'normal', label: 'NORMAL' },
                { key: 'wet', label: 'WET' },
                { key: 'muddy', label: 'MUDDY' },
                { key: 'rock', label: 'ROCK' },
                { key: 'frozen', label: 'FROZEN' },
              ]}
              value={blastDay.conditions.groundConditions}
              w={118}
            />
            <CondCell
              title="Type Of Work"
              options={[
                { key: 'drill_only', label: 'Drill Only' },
                { key: 'drill_to_blast', label: 'Drill to Blast' },
                { key: 'blasting', label: 'Blasting' },
                { key: 'crushing', label: 'Crushing' },
              ]}
              value={blastDay.typeOfWork}
              w={100}
            />
            <TD style={{ borderWidth: 1.5, borderColor: '#000' }}>
              <Text style={[K.bold, K.center, { fontSize: 10 }]}>PROJECT</Text>
              <Text style={[K.val, K.center, { fontSize: 10 }]}>
                {(job?.name ?? '').split(/\s+/).map((w) => w[0]).join('').toUpperCase().slice(0, 3)}
              </Text>
            </TD>
          </TR>
        </T>

        {/* Work Force + nested Equipment */}
        <T>
          <TR shade>
            {wfHead('Work Force', 92)}
            {wfHead('IN', 30)}
            {wfHead('OUT', 30)}
            {wfHead('ST', 22)}
            {wfHead('OT', 22)}
            {wfHead('TRK', 24)}
            {wfHead('TRVL', 26)}
            {wfHead('Asset # (Used/OnSite)', 62)}
            {wfHead('Hrs Start', 36)}
            {wfHead('Hrs End', 36)}
            {wfHead('')}
          </TR>
          {wfRows.map((w, i) => {
            const cell = equipCells[i];
            const cs = { fontSize: 7 };
            return (
              <TR key={i}>
                <TD w={92} textStyle={{ fontSize: 7.5 }}>
                  {`${i + 1}. ${w?.workerName ?? ''}`}
                </TD>
                <TD w={30} textStyle={[K.center, cs]}>{w ? dash(w.timeIn) : ''}</TD>
                <TD w={30} textStyle={[K.center, cs]}>{w ? dash(w.timeOut) : ''}</TD>
                <TD w={22} textStyle={[K.center, cs]}>{w?.straightTime ? String(w.straightTime) : ''}</TD>
                <TD w={22} textStyle={[K.center, cs]}>{w?.overtime ? String(w.overtime) : ''}</TD>
                <TD w={24} textStyle={[K.center, cs]}>{w?.truckHours ? CHECK : ''}</TD>
                <TD w={26} textStyle={[K.center, cs]}>{w?.travelHours ? String(w.travelHours) : ''}</TD>
                {cell?.label ? (
                  <TD w={134} style={{ backgroundColor: '#f0f0f0' }} textStyle={[K.center, K.boldItalic, { fontSize: 6.5 }]}>
                    {cell.label}
                  </TD>
                ) : cell?.item ? (
                  <>
                    <TD w={62} textStyle={[K.center, cs]}>{cell.item.assetNumber}</TD>
                    <TD w={36} textStyle={[K.center, cs]}>{cell.item.hoursStart ? String(cell.item.hoursStart) : ''}</TD>
                    <TD w={36} textStyle={[K.center, cs]}>{cell.item.hoursEnd ? String(cell.item.hoursEnd) : ''}</TD>
                  </>
                ) : (
                  <TD w={134}> </TD>
                )}
                <TD> </TD>
              </TR>
            );
          })}
          {[
            ['# of Drill Holes:', dash(totalHoles)],
            ['Total Vertical Ft Drilled:', dash(Math.round(totalFootage))],
            ['Pattern:', dash(pattern)],
          ].map(([label, value]) => (
            <TR key={label} style={{ backgroundColor: '#f0f0f0' }}>
              <TD w={92} textStyle={[K.bold, { fontSize: 7.5 }]}>{label}</TD>
              <TD w={154} textStyle={[K.val, K.center, { fontSize: 8 }]}>{value}</TD>
              <TD> </TD>
            </TR>
          ))}
        </T>

        {/* Materials + Subcontractors, side by side */}
        <View style={{ flexDirection: 'row', gap: 4, marginTop: 4 }}>
          <View style={{ flex: 1 }}>
            <T>
              <TR shade>
                <TD textStyle={[K.bold, K.center, { fontSize: 7.5 }]}>Materials / Onsite Repairs / Fuel</TD>
              </TR>
              <TR shade>
                {wfHead('Vender', 60)}
                {wfHead('Description')}
                {wfHead('Unit', 32)}
                {wfHead('Total', 40)}
              </TR>
              <TR>
                <TD textStyle={[K.center, K.italic, { fontSize: 6.5 }]}>**Explosives on Back</TD>
              </TR>
              {materials.map((m, i) => (
                <TR key={i}>
                  <TD w={60} textStyle={{ fontSize: 7 }}>{m.vendor}</TD>
                  <TD textStyle={{ fontSize: 7 }}>{m.description}</TD>
                  <TD w={32} textStyle={[K.center, { fontSize: 7 }]}>{m.unit}</TD>
                  <TD w={40} textStyle={[K.center, { fontSize: 7 }]}>{m.total ? `$${m.total}` : ''}</TD>
                </TR>
              ))}
              {Array.from({ length: Math.max(0, 7 - materials.length) }, (_, i) => (
                <TR key={`e${i}`}>
                  <TD w={60}> </TD>
                  <TD> </TD>
                  <TD w={32}> </TD>
                  <TD w={40}> </TD>
                </TR>
              ))}
            </T>
          </View>
          <View style={{ flex: 0.9 }}>
            <T>
              <TR shade>
                <TD textStyle={[K.bold, K.center, { fontSize: 7.5 }]}>Subcontractors / Rentals / Fire Detail</TD>
              </TR>
              <TR shade>
                {wfHead('Vender', 60)}
                {wfHead('Description')}
                {wfHead('Hrs', 26)}
                {wfHead('Total', 40)}
              </TR>
              {subcontractors.map((s, i) => (
                <TR key={i}>
                  <TD w={60} textStyle={{ fontSize: 7 }}>{s.vendor}</TD>
                  <TD textStyle={{ fontSize: 7 }}>{s.description}</TD>
                  <TD w={26} textStyle={[K.center, { fontSize: 7 }]}>{s.hours ? String(s.hours) : ''}</TD>
                  <TD w={40} textStyle={[K.center, { fontSize: 7 }]}>{s.total ? `$${s.total}` : ''}</TD>
                </TR>
              ))}
              {Array.from({ length: Math.max(0, 4 - subcontractors.length) }, (_, i) => (
                <TR key={`e${i}`}>
                  <TD w={60}> </TD>
                  <TD> </TD>
                  <TD w={26}> </TD>
                  <TD w={40}> </TD>
                </TR>
              ))}
            </T>
          </View>
        </View>

        <T style={{ marginTop: 4 }}>
          <TR>
            <TD w={50} style={{ minHeight: 55 }} textStyle={[K.bold, { color: '#c00' }]}>NOTES:</TD>
            <TD style={{ minHeight: 55, justifyContent: 'flex-start' }} textStyle={[K.val, { fontSize: 8 }]}>
              {dailyReport.notes ?? ''}
            </TD>
          </TR>
        </T>
        <Footer text={footer} />
      </Page>

      {/* ============ PAGE 2: MATERIALS SUMMARY ============ */}
      <Page size="LETTER" style={K.page}>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 }}>
          <View style={{ flex: 1, alignItems: 'center' }}>
            <Text style={{ fontSize: 17, fontFamily: 'Helvetica-Bold' }}>BAYSTATE BLASTING</Text>
            <Text style={{ fontSize: 14, fontFamily: 'Helvetica-Bold' }}>MATERIALS SUMMARY</Text>
          </View>
          <Text style={[K.val, { fontSize: 12, borderWidth: 1.5, borderColor: '#000', paddingHorizontal: 6, paddingVertical: 2, alignSelf: 'flex-start' }]}>
            {fmtDate(blastDay.date)}
          </Text>
        </View>

        <View style={{ borderBottomWidth: 1, borderBottomColor: '#000', paddingBottom: 2, marginBottom: 6 }}>
          <Text>
            <Text>Company: </Text>
            <Text style={K.val}>Baystate Blasting, Inc. — {job?.name} — {fmtDate(blastDay.date)}</Text>
          </Text>
        </View>

        {summaryGroups.map((group) => {
          const items = products.filter((p) => group.cats.includes(p.category as ProductCategory));
          return (
            <View key={group.title} style={{ marginBottom: 6 }}>
              <Text style={[K.bold, { fontSize: 8.5, marginBottom: 2 }]}>{group.title}</Text>
              <T>
                {items.length === 0 ? (
                  <TR>
                    <TD w={220}> </TD>
                    <TD w={34} textStyle={K.center}>{group.unit}</TD>
                    <TD w={55} textStyle={K.center}>—</TD>
                    <TD style={{ borderRightWidth: 0.75 }}> </TD>
                  </TR>
                ) : (
                  items.map((p, i) => (
                    <TR key={i}>
                      <TD w={220} textStyle={K.right}>{p.productName}</TD>
                      <TD w={34} textStyle={K.center}>{group.unit}</TD>
                      <TD w={55} textStyle={[K.val, K.center]}>
                        {group.unit === 'LB' ? p.totalWeight.toFixed(0) : String(p.quantity)}
                      </TD>
                      <TD> </TD>
                    </TR>
                  ))
                )}
              </T>
            </View>
          );
        })}

        <Text style={[K.bold, { fontSize: 8.5, marginBottom: 2 }]}>Detonators</Text>
        <T style={{ marginBottom: 6 }}>
          {detonators.length === 0 ? (
            <TR>
              <TD w={220}> </TD>
              <TD w={34} textStyle={K.center}>EA</TD>
              <TD w={55} textStyle={K.center}>—</TD>
              <TD> </TD>
            </TR>
          ) : (
            detonators.map((dd, i) => (
              <TR key={i}>
                <TD w={220} textStyle={K.right}>{`${dd.name} ${dd.unitLength}`}</TD>
                <TD w={34} textStyle={K.center}>EA</TD>
                <TD w={55} textStyle={[K.val, K.center]}>{String(dd.quantity)}</TD>
                <TD> </TD>
              </TR>
            ))
          )}
        </T>

        <Text style={[K.bold, { fontSize: 8.5, marginBottom: 2 }]}>LEAD IN LINE</Text>
        <View style={{ width: 320 }}>
          <T>
            <TR>
              <TD w={220} textStyle={K.right}>Lead Line (LF)</TD>
              <TD w={34} textStyle={K.center}>LF</TD>
              <TD w={55} textStyle={[K.val, K.center]}>{dash(explosiveUsage?.leadLine)}</TD>
            </TR>
          </T>
        </View>

        {/* Daily totals banner */}
        <View style={{ borderWidth: 1.5, borderColor: '#1a365d', borderRadius: 4, padding: 8, marginTop: 12 }}>
          <Text style={[K.bold, K.center, { fontSize: 9, color: '#1a365d', marginBottom: 5 }]}>
            DAILY TOTALS SUMMARY
          </Text>
          <View style={{ flexDirection: 'row', justifyContent: 'space-around' }}>
            {[
              [agentLbs.toFixed(0), 'Blasting Agents (lbs)'],
              [heLbs.toFixed(0), 'High Explosives (lbs)'],
              [boosterLbs.toFixed(1), 'Boosters (lbs)'],
            ].map(([v, label]) => (
              <View key={label} style={{ alignItems: 'center' }}>
                <Text style={[K.val, { fontSize: 13 }]}>{v}</Text>
                <Text style={{ fontSize: 6.5, color: '#666' }}>{label}</Text>
              </View>
            ))}
            <View style={{ alignItems: 'center' }}>
              <Text style={[K.val, { fontSize: 16, color: '#DD6B20' }]}>{totalLbs.toFixed(1)}</Text>
              <Text style={[K.bold, { fontSize: 7, color: '#1a365d' }]}>TOTAL LBS SHOT</Text>
            </View>
            <View style={{ alignItems: 'center' }}>
              <Text style={[K.val, { fontSize: 13 }]}>{detonatorCount ? String(detonatorCount) : '—'}</Text>
              <Text style={{ fontSize: 6.5, color: '#666' }}>Detonators (ea)</Text>
            </View>
          </View>
        </View>
        <Footer text={footer} />
      </Page>
    </Document>
  );
}

export async function buildDailyReportPdf(blastDayId: string): Promise<Blob> {
  const blastDay = await db.blastDays.get(blastDayId);
  if (!blastDay) throw new Error('work day not found');
  const dailyReport = await db.dailyReports.where('blastDayId').equals(blastDayId).first();
  if (!dailyReport) throw new Error('daily report not found');
  const job = await getJobView(blastDay.jobId);
  const blastLog = await db.blastLogs.where('blastDayId').equals(blastDayId).first();
  const shots = blastLog ? await db.shots.where('blastLogId').equals(blastLog.id).sortBy('shotNumber') : [];
  const explosiveUsage = blastLog
    ? await db.explosiveUsages.where('blastLogId').equals(blastLog.id).first()
    : undefined;
  const workForce = (await db.workForceEntries.where('dailyReportId').equals(dailyReport.id).toArray()).sort(
    (a, b) => a.rowNumber - b.rowNumber,
  );
  const equipment = await db.equipmentEntries.where('dailyReportId').equals(dailyReport.id).toArray();
  const materials = await db.materialEntries.where('dailyReportId').equals(dailyReport.id).toArray();
  const subcontractors = await db.subcontractorEntries.where('dailyReportId').equals(dailyReport.id).toArray();
  return pdf(
    <DailyReportDoc
      blastDay={blastDay}
      job={job}
      dailyReport={dailyReport}
      shots={shots}
      explosiveUsage={explosiveUsage}
      workForce={workForce}
      equipment={equipment}
      materials={materials}
      subcontractors={subcontractors}
    />,
  ).toBlob();
}
