// Incident Report — searchable PDF (insurance-grade paper copy).
import { pdf } from '@react-pdf/renderer';
import { db } from '@/db';
import { getJobView } from '@/lib/jobContext';
import { formatDate } from '@/lib/utils';
import type { Incident, Job } from '@/db/schema';
import { Document, Footer, HeaderBar, K, Page, T, TD, TR, Text } from './kit';

export const INCIDENT_TITLE = {
  blasting: 'Blasting Incident Report',
  utility: 'Utility Strike Report',
  asset: 'Company Asset Incident Report',
} as const;

function Row({ label, value }: { label: string; value: string | number | null | undefined }) {
  return (
    <TR>
      <TD w={170} textStyle={K.bold}>{label}</TD>
      <TD>{value === undefined || value === null || value === '' ? '—' : String(value)}</TD>
    </TR>
  );
}

function SectionHead({ title }: { title: string }) {
  return (
    <TR shade>
      <TD textStyle={[K.bold, K.center]}>{title}</TD>
    </TR>
  );
}

function IncidentDoc({
  incident,
  job,
  companyName,
}: {
  incident: Incident;
  job?: Job;
  companyName: string;
}) {
  return (
    <Document title={`${INCIDENT_TITLE[incident.type]} — ${formatDate(incident.date)}`}>
      <Page size="LETTER" style={K.page}>
        <HeaderBar companyName={companyName} title={INCIDENT_TITLE[incident.type]} />
        <T style={{ marginBottom: 6 }}>
          <Row label="Date / time" value={`${formatDate(incident.date)} ${incident.time}`} />
          <Row label="Job" value={job ? `${job.name} — ${job.customer}` : undefined} />
          <Row label="Reported by" value={incident.reportedByName} />
          <Row label="Description" value={incident.description} />
        </T>
        {incident.type === 'blasting' ? (
          <T style={{ marginBottom: 6 }}>
            <SectionHead title="Structure & readings" />
            <Row label="Structure" value={incident.structureType} />
            <Row label="Structure address" value={incident.structureAddress} />
            <Row label="Owner" value={[incident.ownerName, incident.ownerPhone].filter(Boolean).join(' · ')} />
            <Row label="Owner address" value={incident.ownerAddress} />
            <Row label="Pre-blast survey" value={incident.preBlastSurvey} />
            <Row label="PPV (in/s)" value={incident.ppv ?? undefined} />
            <Row label="Air overpressure (dB)" value={incident.db ?? undefined} />
          </T>
        ) : null}
        {incident.type === 'utility' ? (
          <T style={{ marginBottom: 6 }}>
            <SectionHead title="Utility details" />
            <Row label="Provider" value={incident.utilityProvider} />
            <Row label="Dig Safe #" value={incident.digsafeNumber} />
            <Row label="Marking" value={incident.utilityMarked} />
            <Row label="Utility type" value={incident.utilityKind?.replace(/_/g, ' ')} />
          </T>
        ) : null}
        {incident.type === 'asset' ? (
          <T style={{ marginBottom: 6 }}>
            <SectionHead title="Asset details" />
            <Row label="Kind" value={incident.assetIncidentKind?.replace(/_/g, ' ')} />
            <Row
              label="Police called"
              value={incident.policeCalled === undefined ? undefined : incident.policeCalled ? 'yes' : 'no'}
            />
            <Row label="Other party" value={incident.otherParty} />
          </T>
        ) : null}
        <T>
          <TR>
            <TD>
              <Text>
                <Text style={K.bold}>Filed by: </Text>
                <Text>{incident.reportedByName} — ________________</Text>
              </Text>
            </TD>
            <TD w={150}>
              <Text>
                <Text style={K.bold}>Date: </Text>
                <Text>{formatDate(incident.date)}</Text>
              </Text>
            </TD>
          </TR>
        </T>
        <Footer text={`Generated by ShotLog — ${companyName} — ${formatDate(incident.date)}`} />
      </Page>
    </Document>
  );
}

export async function buildIncidentPdf(incidentId: string): Promise<Blob> {
  const incident = await db.incidents.get(incidentId);
  if (!incident) throw new Error('incident not found');
  const job = await getJobView(incident.jobId);
  const company = await db.companySettings.get('companySettings-singleton');
  return pdf(
    <IncidentDoc
      incident={incident}
      job={job}
      companyName={company?.companyName || 'Baystate Blasting, Inc.'}
    />,
  ).toBlob();
}
